# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["master"]
    tags: "**"
  pull_request:
    branches: ["master", "feature/**"]

jobs:

  build:
    runs-on: ubuntu-18.04
    env:
      PACKAGE_ROOT : github.com/stevejefferson/trac2gitea
      
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        go build -o trac2gitea -v

    - name: Generate Mocks
      run: |
        go install github.com/golang/mock/mockgen@v1.4.3
        mockgen -destination=mock_markdown/converter.go $PACKAGE_ROOT/markdown Converter
        mockgen -destination=accessor/mock_gitea/accessor.go $PACKAGE_ROOT/accessor/gitea Accessor
        mockgen -destination=accessor/mock_trac/accessor.go $PACKAGE_ROOT/accessor/trac Accessor
        
    - name: Test
      run: |
        go test ./...
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: |
          ./trac2gitea
